apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecr
  labels:
    app: eks-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-test
  template:
    metadata:
      labels:
        app: eks-test
    spec:
      containers:
      - name: ecr
        image: 282800251275.dkr.ecr.ap-southeast-2.amazonaws.com/ecr:latest
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent